# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccic" do
  version "0.4.2"

  on_macos do
    on_arm do
      sha256 "11db5d71a821cd473784ab26829be14e2fb175bef67e7047c53d3f3784b32e00"
      url "https://github.com/spin-up-solutions/ccic-tool/releases/download/v#{version}/ccic_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9de9b4c0420243eb868b0f4f85fc29e96de983e22aa7d62e3399d2d754ace2fc"
      url "https://github.com/spin-up-solutions/ccic-tool/releases/download/v#{version}/ccic_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "429e6890b4c705ef2b7f64580098d31bda41b4b17501756b277375a472cb55bb"
      url "https://github.com/spin-up-solutions/ccic-tool/releases/download/v#{version}/ccic_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7638a5eb2141bb81b36fec8ceca08937ffc9e2cc584d166c658e050ffbd997b3"
      url "https://github.com/spin-up-solutions/ccic-tool/releases/download/v#{version}/ccic_linux_amd64.tar.gz"
    end
  end

  name "ccic"
  desc "Run Claude Code in a container, isolated from your dev environment"
  homepage "https://github.com/spin-up-solutions/ccic-tool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccic"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccic"]
    end
  end

  # No zap stanza required
end
