# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccic" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "c161ac2236375043da6cbf47f947417252a78eba854b90b6eeeb2094ec5520c7"
      url "https://github.com/spin-up-solutions/ccic-tool/releases/download/v#{version}/ccic_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9577a41028cfec7951dbd37194598667e8db4f4a03a512da5ed05cf7736f19bf"
      url "https://github.com/spin-up-solutions/ccic-tool/releases/download/v#{version}/ccic_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "62d3d7327a7fea00588484b774dbabe2f86fa89661f574a1e689fa0b89b58068"
      url "https://github.com/spin-up-solutions/ccic-tool/releases/download/v#{version}/ccic_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c116174aa43b38b3ea45b67476fd2e89506ad6a2826ca8563348b21db66efe46"
      url "https://github.com/spin-up-solutions/ccic-tool/releases/download/v#{version}/ccic_linux_amd64.tar.gz"
    end
  end

  name "ccic"
  desc "Run Claude Code in a container, isolated from your dev environment"
  homepage "https://github.com/spin-up-solutions/ccic-tool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccic"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccic"]
    end
  end

  # No zap stanza required
end
