# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccic" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "f7262a9e7affd1dc93a6146c85a8b1180a92f50e77ac309449f574c6aa5f502a"
      url "https://github.com/spin-up-solutions/ccic-tool/releases/download/v#{version}/ccic_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "77d1731fb6a4004e368921b9fbd28f988a26e9a887cedb0cab5f67b2b1bd5828"
      url "https://github.com/spin-up-solutions/ccic-tool/releases/download/v#{version}/ccic_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8e8362764753ff720e2d0fdbab7834fe3f8dc9b175fa1964d97d420d28f0f706"
      url "https://github.com/spin-up-solutions/ccic-tool/releases/download/v#{version}/ccic_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c9b2ef57cc1acff78a523dfae5a75c5223a6e9398a843345886a7c5aa3e75fc1"
      url "https://github.com/spin-up-solutions/ccic-tool/releases/download/v#{version}/ccic_linux_amd64.tar.gz"
    end
  end

  name "ccic"
  desc "Run Claude Code in a container, isolated from your dev environment"
  homepage "https://github.com/spin-up-solutions/ccic-tool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccic"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccic"]
    end
  end

  # No zap stanza required
end
